dev-tools-installer:
  pkg.installed:
    - pkgs:   
      - apt-transport-https 
      - ca-certificates         
      - binutils
      - build-essential
      - cmake
      - coreutils
      - curl
      - gdb
      - gnupg-agent 
      - htop
      - httpie
      - libspatialindex-dev
      - make
      - tar
      - software-properties-common 
      - ubuntu-restricted-extras
      - wget
      - valgrind
      - vim
      - zip
      - xclip
